server:
  port: 8180
agency-app:
  use-local-database: ${AGENCY_APP_LOCAL_DB:true}
spring:
  application:
    name: agency-app

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:agency_db}
    username: ${POSTGRES_USER:demo}
    password: ${POSTGRES_PASSWORD:demo}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect